### ISSUE TITLE
BadPixelSigmaFilterModule can't read data

### ISSUE THREAD

**Issue by benassa-de-glassa** [PynPoint/PynPoint#355]
Hey @tomasstolker , 
I'm consistently getting the error message below when running the BadPixelSigmaFilterModule, I can't figure out the reason...

Edit: I found this bugreport: 
https://github.com/h5py/h5py/issues/480

Do you have an idea how to solve this?

`Running BadPixelSigmaFilterModule...............................Process StackReader-49:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data/ipa/meyer/bschmidh/PynPoint/pynpoint/util/multistack.py", line 72, in run
    tmp_data = self.m_data_in_port[i:j, ]
  File "/data/ipa/meyer/bschmidh/PynPoint/pynpoint/core/dataio.py", line 431, in __getitem__
    data = self._m_data_storage.m_data_bank[self._m_tag][item]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/bschmidh/.local/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 573, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (wrong B-tree signature)`

Thanks, Bene

**Comment by tomasstolker** [comment]
Do you have the latest implementations from Github?

`BadPixelSigmaFilterModule` has two output ports whereas the multiprocessing functionalities of `util.multistack` can only handle one. So `map_out_tag` should be set to `None` if `CPU > 1`. A warning is printed if this is not the case.

Let me know if this solves the problem.

**Comment by benassa-de-glassa** [comment]
yep, that solved it, thanks a lot
